#Significa que no se pueden utilizar para nombrar variables, ya que cada palabra tiene un uso especifico en el lenguajede python.
print("Palabras reservadas en python")
print()
def palabras_reservadas():
    print("continue")
    print("finally")
    print("import")
    print("assert")
    print("lambda")
    print("return")
    print("except")
    print("global")
    print("raise")
    print("break")
    print("yield")
    print("print")
    print("class")
    print("while")
    print("from")
    print("elif")
    print("exec")
    print("else")
    print("try")
    print("not")
    print("def")
    print("and")
    print("for")
    print("del")
    print("or")
    print("if")
    print("in")
    print("is")

palabras_reservadas()
