#include <bits/stdc++.h>

///INCLUYE TODAS LAS LIBREÍAS DE CODEBLOCKS
///EVITA ESTAR RECORDANDO LIBREÍAS ESPECÍFICAS
///NO ES ESTÁNDAR DE GNU C++ (ASÍ QUE ES PROBABLE QUE FALLE SI SE COMPILA CON ALGÚN COMPILADOR QUE NO SEA GCC)
///USARLO PUEDE INCLUIR COSAS INNECESARIAS Y EL TIEMPO DE COMPILACIÓN PUEDE AUMENTAR
